# Generated by Django 3.2.7 on 2024-03-01 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='age',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.AddField(
            model_name='booking',
            name='bed',
            field=models.CharField(choices=[('BedNo:1', 'BedNo:1'), ('BedNo:2', 'BedNo:2'), ('BedNo:3', 'BedNo:3'), ('BedNo:4', 'BedNo:4'), ('BedNo:5', 'BedNo:5')], default='BedNo:1', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(choices=[('Room1', 'Room1'), ('Room2', 'Room2'), ('Room3', 'Room3'), ('Room4', 'Room4'), ('Room5', 'Room5'), ('Room6', 'Room6')], default='Room1', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_number', models.CharField(max_length=12)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('student', 'Student'), ('working', 'Working')], max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('parents_contact', models.CharField(blank=True, max_length=12, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
