# Generated by Django 3.2.7 on 2024-03-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0002_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='semail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='sname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='spassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='susernanme',
            new_name='usernanme',
        ),
    ]
