# Generated by Django 3.2.7 on 2024-03-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodlist',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=200)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='foods')),
                ('Food_category', models.CharField(choices=[('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Tea', 'Tea'), ('Dinner', 'Dinner')], default='Lunch', max_length=200)),
            ],
        ),
    ]
