# Generated by Django 3.2.7 on 2024-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=100, null=True)),
                ('susernanme', models.CharField(blank=True, max_length=100, null=True)),
                ('semail', models.EmailField(max_length=254, unique=True)),
                ('spassword', models.CharField(max_length=128)),
            ],
        ),
    ]
