# Generated by Django 3.2.7 on 2024-03-01 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('Room1', 'Room1'), ('Room2', 'Room2'), ('Room3', 'Room3')], default='Room1', max_length=20)),
                ('name', models.CharField(choices=[('BedNo:1', 'BedNo:1'), ('BedNo:2', 'BedNo:2'), ('BedNo:3', 'BedNo:3')], default='BedNo:1', max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
